### PR TITLE
sort message list to make build reproducible

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by v4hn** [comment]
@dirk-thomas: Could you have a quick look please? There are two open pull-requests in this repo and both are straight forward bug-fixes.
@airballking seems to have gone missing from anything not related to his lab and didn't respond to the other request within _a year after ping_.  This request here works towards [reproducible builds](https://wiki.debian.org/ReproducibleBuilds) in ROS and is an utterly trivial change.

please merge

**Comment by airballking** [comment]
@v4hn Nice to meet you! :) 

I am indeed very busy with my lab-work, and on top of that not familiar with the internals of the genmsg mechanisms. Hence, I would prefer if @dirk-thomas takes the lead on this. However, if he also cannot spare the time because ROS2.0  has priority, I can try to find time (and a lab-mate to help).

**Comment by v4hn** [comment]
On Wed, Aug 10, 2016 at 01:28:40PM -0700, Georg Bartels wrote:

> @v4hn Nice to meet you! :)

ok, is that sarcasm? I'm not sure :)
Maybe we'll get the chance to meet in a while. Michael Beetz invited me for some popcorn
and I plan to come back to this offer once we have our PR2 setup back up and running here in Hamburg. :-)

Thanks for the sign of life!

**Comment by moesenle** [comment]
The change is in deed trivial and I think it is actually quite important. Merging it... The release of this package has to be done by someone else though.

**Comment by airballking** [comment]
@v4hn No, that was not an attempt at sarcasm. I was trying to be friendly and express the fact that I am indeed very busy with lab work these days. 

@moesenle Thanks for merging! I will test that message generation still works, and if it does trigger the release.

**Pull request merged**
